name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: |
        cd src\Jackett.Server
        dotnet build --configuration Release
        cd bin\Release\netcoreapp3.1
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: server
        # Directory containing files to upload
        path: bin\Release\netcoreapp3.1
