name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: |
        ls
        cd src/Jackett.Server
        dotnet build --configuration Release        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: server
        # Directory containing files to upload
        path: src/Jackett.Server/bin/Release/netcoreapp3.1
